### ISSUE TITLE
runpython

### ISSUE THREAD

**Issue by cosir888** [BKN46/ToogleBot#1]
我看到一项功能 runpython
是否可以实现通过给机器人QQ发送账号密码来执行我的爬虫脚本？？

**Comment by BKN46** [comment]
不可以
这个功能本身有一些安全风险，所以运行的作用域和可调用库都做了限制，只能执行一些简单的脚本计算读取stdout

**Comment by cosir888** [comment]
明白了，感谢回复！一直想实现QQ机器人执行我的py脚本。我再找找。
